import WeStyleSheet from "../../../components/WeStyleSheet";
// import {
//     StyleSheet,
//     Dimensions
// } from 'react-native';
import colorStyle from "../../../components/color/styles"
import fontStyle from "../../../components/font/styles"
export default WeStyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colorStyle.white,
    },
    bg:{
        height:544,
    },
    location:{
        position:"absolute",
        alignSelf:"center",
    },
    image:{
        width:204,
        height:204,
        top:50,
        borderRadius:204,
        justifyContent:"center",
        backgroundColor:"#33b6ed",
    },
    pic:{
        display:"flex",
        width:179,
        height:179,
        borderRadius:179,
        alignSelf:"center",
    },
    name:{
        fontSize:fontStyle.font,
        color:"#9fe3ff",
        top:264,
    },
    block:{
        fontSize:fontStyle.fontTitleBig,
        color:colorStyle.white,
        top:332
    },
    content:{
        marginLeft:46,
        marginRight:46,
    },
    showMessage:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        justifyContent:"space-around",
    },
    address:{
        fontSize:fontStyle.fontTitle,
        color:colorStyle.title,
        marginBottom:45,
        marginTop:83,
        textAlign:"center"
    },
    message:{
        fontSize:fontStyle.fontTitleBig,
        color:colorStyle.info,
        marginBottom:73,
    },
    line:{
        width:2,
        height:160,
        borderRightWidth:2,
        borderColor:colorStyle.border,
        marginTop:83,
    },
    profit:{
        top:-60,
        zIndex:2,
        paddingTop:8,
        paddingBottom:8,
        paddingLeft:8,
        paddingRight:8,
        backgroundColor:colorStyle.white,
        borderRadius:20,
    },
    profitBox:{
      backgroundColor:"rgba(0,164,232,1)",
        borderRadius:20,
    },
    profitName:{
        width:538,
        fontSize:fontStyle.font,
        color:colorStyle.white,
        textAlign:"center",
        paddingTop:25,
        paddingBottom:25,
    },
    item:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        justifyContent:"space-between",
        alignItems:"center",
        borderTopWidth:1,
        borderColor:colorStyle.border,
    },
    show:{
       display:"flex",
       flexDirection:"row",
       flexWrap:"nowrap",
        alignItems:"center",
        marginTop:30,
        marginBottom:30,
    },
    iconFont:{
        width:106,
        height:106,
        borderRadius:106,
        marginRight:28,
    },
    stage:{
        fontSize:fontStyle.font,
        color:colorStyle.info,
    },
    introduction:{
        height:220,
        borderWidth:1,
        borderColor:colorStyle.border,
        marginBottom:54,
    },
    inp:{
        paddingTop:29,
        paddingBottom:0,
        paddingLeft:26,
    }
})