import WeStyleSheet from "../../../components/WeStyleSheet";
// import {
//     StyleSheet,
//     Dimensions
// } from 'react-native';
import colorStyle from "../../../components/color/styles"
import fontStyle from "../../../components/font/styles"
export default WeStyleSheet.create({
    container:{
        flex:1,
    },
    searchBar:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        alignItems:"center",
        paddingTop:40,
        paddingBottom:30,
        paddingLeft:46,
        backgroundColor:colorStyle.white,
        marginTop:0,
        borderBottomWidth:1,
        borderStyle:"solid",
        borderBottomColor:colorStyle.border,

    },
    pic:{
        flexGrow:0,
        width:52,
        height:52,
        marginRight:30
    },
    title:{
        flexGrow:1,
        fontSize:fontStyle.font,
        color:"#c5c8cb",
        padding:0,
    },
    content:{
        backgroundColor:colorStyle.white,
        marginTop:25,
        borderTopWidth:1,
        borderStyle:"solid",
        borderTopColor:colorStyle.border,
    },
    operation:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        justifyContent:"space-between",
        paddingTop:38,
        paddingBottom:70,
    },
    time:{
        fontSize:fontStyle.fontContent,
        color:colorStyle.title,
        marginLeft:46,
    },
    del:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        justifyContent:"flex-start",
        alignItems:"center",
    },
    delPic:{
        marginRight:18,
        width:30,
        height:36,
    },
    delText:{
        fontSize:fontStyle.fontNav,
        color:colorStyle.title,
        marginRight:46,
    },
    item:{
        borderBottomWidth:1,
        borderStyle:"solid",
        borderBottomColor:colorStyle.border,
        marginLeft:46,
        marginRight:46,
    },
    stage:{
      fontSize:fontStyle.fontContent,
      color:colorStyle.active,
      marginBottom:16,
        marginLeft:46,
        marginRight:46,
    },
    info:{
        fontSize:fontStyle.fontContent,
        color:colorStyle.info,
        lineHeight:66,
        marginLeft:46,
        marginRight:46,
    },
    picture:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"wrap",
        justifyContent:"flex-start",
        borderBottomWidth:1,
        borderStyle:"solid",
        borderBottomColor:colorStyle.border,
        marginLeft:46,
        marginRight:46,

    },
    image:{
        width:208,
        height:168,
        marginRight:52,
        marginBottom:40,
        marginTop:30,
    },
    btn:{
        display:"flex",
        flexDirection:"row",
        flexWrap:"nowrap",
        justifyContent:"flex-end",
        paddingTop:34,
        paddingBottom:34,
        borderBottomWidth:1,
        borderStyle:"solid",
        borderBottomColor:colorStyle.border,
    },
    edit:{
       borderWidth:1,
       borderStyle:"solid",
       borderColor:colorStyle.active,
        borderRadius:5,
    },
    send:{
        backgroundColor:colorStyle.active,
        marginLeft:50,
        marginRight:46,
    },
    word:{
        fontSize:fontStyle.font,
        color:colorStyle.active,
        marginLeft:90,
        marginRight:90,
        marginTop:30,
        marginBottom:30,
    },
    sendword:{
      color:colorStyle.white,
    },
    prompt:{
        fontSize:fontStyle.fontContent,
        color:"#c5c8cb",
        textAlign:"center",
        marginTop:50,
        marginBottom:9,
    },
    touch:{
        width:178,
        height:178,
        marginTop:245,
        alignSelf:"center",
    },
    empty:{
        display:"none",
    },
    logo:{
        width:562,
        height:492,
        marginTop:192,
        marginBottom:108,
        alignSelf:"center",
    },
    description:{
        fontSize:fontStyle.fontContent,
        color:"#a4a9ad",
        lineHeight:28,
        alignSelf:"center",
    }
})